### ISSUE TITLE
Install prometheus and Grafana

### ISSUE THREAD

**Issue by manics** [IDR/k8s-analysis-deploy#2]
Looks like it's easier than expected:
- https://github.com/jupyterhub/mybinder.org-deploy/blob/master/mybinder/values.yaml
- https://github.com/jupyterhub/mybinder.org-deploy/tree/master/config

**Comment by manics** [comment]
To be decided: can we make this public? Grafana is used for visualisation, but anyone with knowledge can manipulate the backend API calls to obtain any information held in prometheus. For example, this might allow current users to be identified from the container names:
<img width="466" alt="screen shot 2018-04-25 at 21 12 42" src="https://user-images.githubusercontent.com/1644105/39285516-a4658aa2-48cd-11e8-8c2d-a99b3634491c.png">

On the other hand if we have no concerns with this information being public we could make prometheus completely open too.

**Comment by joshmoore** [comment]
I think I'm more in favor of having it public.

**Comment by manics** [comment]
Background info for this discussion https://github.com/grafana/grafana/issues/1826#issuecomment-95167489

**Comment by manics** [comment]
My vote: public grafana, private prometheus. You can query all prometheus data if you manipulate the grafana API, but it'll be mostly obscured.

**Comment by manics** [comment]
This was done: https://github.com/IDR/k8s-analysis-deploy/pull/6
